//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace HL.IdentityUtility
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HTTPResponse
    {

       
        private string error_messageField;
        private int error_numberField;
        private string key_field;
        private string code_field;
        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        
        /// <remarks/>
        public string error_message
        {
            get
            {
                return this.error_messageField;
            }
            set
            {
                this.error_messageField = value;
            }
        }

        /// <remarks/>
        public int error_number
        {
            get
            {
                return this.error_numberField;
            }
            set
            {
                this.error_numberField = value;
            }
        }
        public string key
        {
            get
            {
                return this.key_field;
            }
            set
            {
                this.key_field = value;
            }
        }
        [XmlElement(IsNullable = true)]
        public string code
        {
            get
            {
                return this.code_field;
            }
            set
            {
                this.code_field = value;
            }
        }
        public HTTPResponse()
        {

        }
        public HTTPResponse(int errorCode, string msg)
        {
            this.error_numberField = errorCode;
            this.error_messageField = msg;
        }
    }
}
