using System.Text;
using System.Xml;
using System.Xml.Serialization;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace HL.Identity
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HLIdentityDataResult
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HLIdentityData
    {
        private string _name;
        private int _id;
        private DateTime _lastModifyDateTime;
        private string _username;
        private string _password;

        public HLIdentityData()
        {
        }

        /// <summary>
        /// Name
        /// </summary>
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        /// <summary>
        /// LastModifyDateTime
        /// </summary>
        /// TODO (CD): Add nullable attribute if field is allowed to be null 
        /// [XmlElement(IsNullable = true)]
        /// TODO (CD): Add DataType attribute if field has a specific type 
        /// [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        /// [System.Xml.Serialization.XmlElementAttribute(DataType = "hexBinary")]
        public DateTime LastModifyDateTime
        {
            get
            {
                return _lastModifyDateTime;
            }
            set
            {
                _lastModifyDateTime = value;
            }
        }

        /// <summary>
        /// UserName
        /// </summary>
        public string Username
        {
            get
            {
                return _username;
            }
            set
            {
                _username = value;
            }
        }

        /// <summary>
        /// Password
        /// </summary>
        public string Password
        {
            get
            {
                return _password;
            }
            set
            {
                _password = value;
            }
        }

        /// <summary>
        /// Write HLIdentityData to a file
        /// </summary>
        /// <param name="filename"></param>
        /// <exception cref="Exception"></exception>
        public void writeToFile(string filename)
        {
            StreamWriter stWriter = null;
            XmlSerializer xmlSerializer;
            XmlDocument doc = new XmlDocument();
            MemoryStream memStream;

            try
            {
                xmlSerializer = new XmlSerializer(this.GetType());
                memStream = new MemoryStream();
                stWriter = new StreamWriter(memStream);
                xmlSerializer.Serialize(stWriter, this);
                doc.PreserveWhitespace = true;
                doc.LoadXml(Encoding.ASCII.GetString(memStream.GetBuffer()));
                doc.Save(filename);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            finally
            {
                if (stWriter != null)
                    stWriter.Close();
            }
        }

        /// <summary>
        /// Write HLIdentityData to a string
        /// </summary>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        public string writeToString()
        {
            StreamWriter stWriter = null;
            StreamReader stReader = null;
            XmlSerializer x;
            XmlDocument doc = new XmlDocument();
            MemoryStream memStream = null;
            string strXML = "";

            try
            {
                x = new XmlSerializer(this.GetType());
                memStream = new MemoryStream();
                stWriter = new StreamWriter(memStream);
                x.Serialize(stWriter, this);
                stReader = new StreamReader(memStream);
                memStream.Position = 0;
                strXML = stReader.ReadToEnd();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            finally
            {
            }

            return strXML;
        }
    }
}
